mysql:
  host: localhost
  port: 3306
  config: "charset=utf8&parseTime=true"
  db: blog_test
  user: root
  password: "123123"
  log_level: dev
logger:
  level: info
  prefix: '[GoBlog]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 9090
  env: release
upload:
  size: 20
  path: uploads/file
site_Info:
  created_at: "2025-04-14"
  bei_an: "5201019"
  title: Jaory的个人博客
  qq_image: ""
  version: "1.2"
  email: 2585@qq.com
  wechat_image: ""
  name: ""
  job: 后端开发
  addr: 福建厦门
  slogan: 天天向上
  slogan_en: up and up
  web: ""
  github_url: ""
qq:
  app_id: xx
  key: xxxx
  redirect: xx
qi_niu:
  enable: true
  access_key: qwwHtwp
  secret_key: X-HELtO
  bucket: amoytudou
  cdn: hn-bkt-clouddn-com-idvcz9d.www.qiniudns.com
  zone: z2
  size: 20
email:
  host: "smtp.qq.com"
  port: 465
  user: "2585925873@qq.com"
  password: "bzfjqyvo"
  defaultFromEmail: "jaory"
  use_ssl: true
  use_tls: false
jwt:
  secret: xxx
  expires: 48
  issuer: xx
redis:
  ip: "127.0.0.1"
  port: 6379
  password: ""
  poolSize: 100
