mysql:
  host: localhost
  port: 3306
  config: ""
  db: blog_test
  user: root
  password: "123123"
  log_level: dev
logger:
  level: info
  prefix: '[GoBlog]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 9090
  env: release
site_Info:
  created_at: "2025-04-14"
  bei_an: "5201019"
  title: Jaory的个人博客
  qq_image: ""
  version: "1.2"
  email: 2585925873@qq.com
  wechat_image: ""
  name: ""
  job: 后端开发
  addr: 福建厦门
  slogan: 天天向上
  slogan_en: up and up
  web: ""
  github_url: ""
jwt:
  secret: xxx
  expires: 48
  issuer: xx
email:
  host:
  port:
  user:
  password:
  defaultFromEmail:
  use_ssL:
  use_tls:
qq:
  app_id :
  key:
  redirect:
qi_niu:
  access_key:
  secret_key:
  bucket:
  cdn:
  zone:
  size:

