mysql:
  host: localhost
  port: 3306
  db: blog_test
  user: root
  password: 123123
  log_level: dev
logger:
  level: info
  prefix: '[GoBlog]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: "0.0.0.0"
  port: 9090
  env: dev
